[package]
name = "blob-archiver-config"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true

[dependencies]
eth2.workspace = true
eyre.workspace = true