[package]
name = "archiver"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true

[dependencies]
eth2.workspace = true

clap.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
tokio.workspace = true
eyre.workspace = true
again.workspace = true
hex.workspace = true
blob-archiver-storage = { path = "../../crates/storage" }
blob-archiver-beacon = { path = "../../crates/beacon" }

